sudo: false
dist: bionic
language: ruby
rvm:
- 2.7
- 3.0
before_install: gem update --system && gem install bundler --no-document
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
script:
- bundle exec rspec --format d
- >
  if [[ "$(rvm current)" = "ruby-"* ]]; then
    bundle exec rubocop
  fi
- >
  if [[ "$(rvm current)" = "ruby-"* ]]; then
    bundle exec codeclimate-test-reporter
  fi
env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
